# Generated by Django 5.2 on 2025-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminplans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminplan",
            name="price_display",
        ),
        migrations.AddField(
            model_name="adminplan",
            name="price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
