# Generated by Django 5.2 on 2025-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminplans", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
