# Generated by Django 5.2 on 2025-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminplans", "0002_adminprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="subscription_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
