# Generated by Django 5.2 on 2025-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminplans", "0003_adminprofile_subscription_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="admin_stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="admin_stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
