# Generated by Django 5.2 on 2025-04-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminplans", "0004_adminprofile_admin_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="auto_renew_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
