# Generated by Django 5.2 on 2025-04-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminplans", "0005_adminprofile_auto_renew_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="next_billing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
