# Generated by Django 5.2 on 2025-04-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminplans", "0007_pendingadminsignup_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("adminTrial", "Free Admin Trial"),
                    ("adminMonthly", "Monthly Admin Plan"),
                    ("adminQuarterly", "Quarterly Admin Plan"),
                    ("adminAnnual", "Annual Admin Plan"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
