# Generated by Django 5.2 on 2026-02-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_area", "0019_adminidentity_subdomain_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPendingSignup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("sale_channel", models.CharField(choices=[("dta_direct", "DTA Direct"), ("admin_white_label", "Admin White Label")], default="admin_white_label", max_length=32)),
                ("offer_code", models.CharField(choices=[("macro_calculator_free", "Macro Calculator (Free)"), ("food_plan_weekly", "Food Plan Weekly"), ("food_plan_monthly", "Food Plan Monthly")], max_length=64)),
                ("billing_cycle", models.CharField(blank=True, default="", max_length=20)),
                ("trial_days", models.PositiveIntegerField(default=0)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("includes_food_plan", models.BooleanField(default=False)),
                ("includes_coaching", models.BooleanField(default=False)),
                ("registration_link_printed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admin", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="client_pending_signups", to="admin_area.adminidentity")),
            ],
            options={
                "verbose_name": "Client Pending Signup",
                "verbose_name_plural": "Client Pending Signups",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sale_channel", models.CharField(default="admin_white_label", max_length=32)),
                ("offer_code", models.CharField(max_length=64)),
                ("billing_cycle", models.CharField(blank=True, default="", max_length=20)),
                ("trial_days", models.PositiveIntegerField(default=0)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("includes_food_plan", models.BooleanField(default=False)),
                ("includes_coaching", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("associated_admin", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="clients", to="admin_area.adminidentity")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="client_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ClientQuestionnaireProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("not_started", "Not Started"), ("in_progress", "In Progress"), ("completed", "Completed")], db_index=True, default="not_started", max_length=20)),
                ("current_step", models.CharField(blank=True, default="", max_length=64)),
                ("answers_json", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="questionnaire_progress", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Client Questionnaire Progress",
                "verbose_name_plural": "Client Questionnaire Progress",
                "ordering": ("-updated_at",),
            },
        ),
    ]
