# Generated by Codex on 2026-02-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_global_food_library"),
        ("client_area", "0003_clientmacroaccesslink_questionnaire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientMealComboSelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("meal_number", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "combo_template",
                    models.ForeignKey(
                        db_column="combo_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_meal_selections",
                        to="core.mealcombotemplate",
                        to_field="combo_id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_combo_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Meal Combo Selection",
                "verbose_name_plural": "Client Meal Combo Selections",
                "ordering": ("user_id", "day_of_week", "meal_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "day_of_week", "meal_number"),
                        name="client_unique_day_meal_combo_selection",
                    )
                ],
            },
        ),
    ]
