# Generated by Codex on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0005_clientfoodpreferencechangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="coaching_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="coaching_term",
            field=models.CharField(
                choices=[
                    ("none", "No Coaching"),
                    ("1_month", "1 Month Coaching"),
                    ("3_months", "3 Months Coaching"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
