# Generated by Codex on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0006_clientprofile_coaching_and_stripe_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
