# Generated by Codex on 2026-02-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0007_clientprofile_cancel_at_period_end"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientQueuedPlanChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_offer_code", models.CharField(max_length=64)),
                ("target_coaching_term", models.CharField(default="none", max_length=20)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("queued_for_period_end_at", models.DateTimeField(blank=True, null=True)),
                ("stripe_checkout_session_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("applied", "Applied"), ("canceled", "Canceled")],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queued_plan_changes",
                        to="client_area.clientprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_plan_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Queued Plan Change",
                "verbose_name_plural": "Client Queued Plan Changes",
                "ordering": ("-created_at",),
            },
        ),
    ]
