# Generated by Django 5.2 on 2026-02-23 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0008_clientqueuedplanchange"),
        ("core", "0002_global_food_library"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientMealPlanGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("algorithm_version", models.CharField(default="wp_v1", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total_steps", models.PositiveSmallIntegerField(default=10)),
                ("current_step", models.PositiveSmallIntegerField(default=0)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("input_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plan_generation_jobs",
                        to="client_area.clientprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Meal Plan Generation Job",
                "verbose_name_plural": "Client Meal Plan Generation Jobs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ClientMealPlanGeneratedMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("meal_number", models.PositiveSmallIntegerField()),
                ("error_code", models.IntegerField(default=0)),
                (
                    "protein1_total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "protein2_total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "carbs1_total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "carbs2_total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "fats1_total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "fats2_total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "combo_template",
                    models.ForeignKey(
                        db_column="combo_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_meal_rows",
                        to="core.mealcombotemplate",
                        to_field="combo_id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_meal_rows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_meals",
                        to="client_area.clientmealplangenerationjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Meal Plan Generated Meal",
                "verbose_name_plural": "Client Meal Plan Generated Meals",
                "ordering": ("day_of_week", "meal_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "day_of_week", "meal_number"),
                        name="client_generated_meal_unique_job_day_meal",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClientMealPlanGenerationStep1Row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_number", models.PositiveSmallIntegerField()),
                ("error_code", models.IntegerField(db_index=True)),
                (
                    "pro_negative",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "carbs_negative",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "fats_negative",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step1_rows",
                        to="client_area.clientmealplangenerationjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Meal Plan Generation Step1 Row",
                "verbose_name_plural": "Client Meal Plan Generation Step1 Rows",
                "ordering": ("meal_number", "error_code"),
                "indexes": [
                    models.Index(
                        fields=["job", "meal_number"], name="client_step1_job_meal_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "meal_number", "error_code"),
                        name="client_meal_plan_step1_unique_row",
                    )
                ],
            },
        ),
    ]
