# Generated by Django 5.2 on 2026-02-24 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0019_adminidentity_subdomain_fields"),
        ("client_area", "0009_clientmealplangenerationjob_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percent Off"),
                            ("fixed_amount", "Fixed Amount Off"),
                        ],
                        default="percent",
                        max_length=20,
                    ),
                ),
                (
                    "percent_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("one_time", "One-Time Purchase"),
                            ("recurring", "Recurring Subscription"),
                            ("either", "Either"),
                        ],
                        default="either",
                        max_length=16,
                    ),
                ),
                ("eligible_offer_codes", models.JSONField(blank=True, default=list)),
                ("eligible_sale_channels", models.JSONField(blank=True, default=list)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("redeemed_count", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "associated_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_codes",
                        to="admin_area.adminidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount Code",
                "verbose_name_plural": "Discount Codes",
                "ordering": ("-created_at",),
            },
        ),
    ]
