# Generated by Django 5.2 on 2026-02-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0010_discountcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpendingsignup",
            name="offer_code",
            field=models.CharField(
                choices=[
                    ("macro_calculator_free", "Macro Calculator (Free)"),
                    ("food_plan_monthly", "Food Plan Monthly"),
                    ("food_plan_monthly_premium", "Food Plan Monthly Premium"),
                ],
                max_length=64,
            ),
        ),
    ]
