# Generated by Django 5.2 on 2026-03-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0014_clientprofile_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpendingsignup",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientpendingsignup",
            name="registration_link",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="clientpendingsignup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clientpendingsignup",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="clientpendingsignup",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
