# Generated by Django 5.2 on 2026-04-30 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0021_clientpendingsignup_questionnaire_payloads"),
        ("core", "0010_proteinshaketemplate_proteinshakeingredientslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProteinShakePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("scoop_count", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_preferences",
                        to="core.proteinshaketemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protein_shake_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Protein Shake Preference",
                "verbose_name_plural": "Client Protein Shake Preferences",
                "ordering": ("user_id", "template_id"),
            },
        ),
        migrations.CreateModel(
            name="ClientProteinShakeIngredientSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_product_data_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "serving_amount",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
                (
                    "serving_unit",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("excluded", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_food_library_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_protein_shake_selections",
                        to="core.foodlibraryitem",
                    ),
                ),
                (
                    "selected_food_override",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protein_shake_ingredient_selections",
                        to="client_area.clientfoodoverride",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_ingredient_selections",
                        to="core.proteinshakeingredientslot",
                    ),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_selections",
                        to="client_area.clientproteinshakepreference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Protein Shake Ingredient Selection",
                "verbose_name_plural": "Client Protein Shake Ingredient Selections",
                "ordering": ("preference_id", "slot__sort_order", "slot_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="clientproteinshakepreference",
            constraint=models.UniqueConstraint(
                fields=("user", "template"), name="client_unique_protein_shake_pref"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientproteinshakepreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("scoop_count__in", [1, 2])),
                name="client_protein_shake_scoop_count_1_or_2",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientproteinshakeingredientselection",
            constraint=models.UniqueConstraint(
                fields=("preference", "slot"), name="client_unique_shake_pref_slot"
            ),
        ),
    ]
