# Generated by Django 5.2 on 2026-04-30 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_area", "0022_clientproteinshakepreference_and_more"),
        ("core", "0010_proteinshaketemplate_proteinshakeingredientslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clientproteinshakepreference",
            name="client_protein_shake_scoop_count_1_or_2",
        ),
        migrations.AlterField(
            model_name="clientproteinshakepreference",
            name="scoop_count",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="clientproteinshakepreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scoop_count__isnull", True),
                    ("scoop_count__in", [1, 2]),
                    _connector="OR",
                ),
                name="client_protein_shake_scoop_count_1_or_2",
            ),
        ),
    ]
