# Generated by Django 5.2.1 on 2025-06-01 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("signup", "Signup"),
                            ("cancel", "Cancel Subscription"),
                            ("stripe_payment", "Stripe Payment Processed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plan_name", models.CharField(max_length=30)),
                ("payment_processed_on", models.DateTimeField(blank=True, null=True)),
                ("subscription_start", models.DateTimeField(blank=True, null=True)),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PendingSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("plan", models.CharField(max_length=50)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("adminTrial", "Free Admin Trial"),
                            ("adminMonthly", "Monthly Admin Plan"),
                            ("adminQuarterly", "Quarterly Admin Plan"),
                            ("adminAnnual", "Annual Admin Plan"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("stripe_price_id", models.CharField(max_length=100)),
                ("price_cents", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PreCheckoutEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("plan_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_canceled", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=True)),
                ("subscription_start", models.DateTimeField()),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                ("next_billing", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "stripe_transaction_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
