# Generated by Django 5.2 on 2025-05-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0002_accounthistory_email_alter_accounthistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthistory",
            name="payment_processed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
