# Generated by Django 5.2 on 2025-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthistory",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accounthistory",
            name="reactivated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accounthistory",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
