# Generated by Django 5.2.1 on 2025-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounthistory",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="email",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="payment_processed_on",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="subscription_end",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="subscription_start",
        ),
        migrations.AddField(
            model_name="accounthistory",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accounthistory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accounthistory",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accounthistory",
            name="event_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="accounthistory",
            name="plan_name",
            field=models.CharField(max_length=50),
        ),
    ]
