# Generated by Django 5.2 on 2025-06-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0003_remove_accounthistory_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="precheckoutemail",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
    ]
