# Generated by Django 5.2 on 2025-05-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0003_accounthistory_payment_processed_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthistory",
            name="stripe_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
