# Generated by Django 5.2.1 on 2025-06-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0004_precheckoutemail_is_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
