# Generated by Django 5.2 on 2025-05-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0004_accounthistory_stripe_transaction_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreCheckoutEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
