# Generated by Django 5.2.1 on 2025-06-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0005_profile_trial_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscription_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
