# Generated by Django 5.2 on 2025-05-08 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0005_precheckoutemail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="canceled_at",
            new_name="subscription_start_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="auto_renew_cancelled",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscription_started_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="trial_start_date",
        ),
        migrations.AddField(
            model_name="profile",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_area.plan",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="reactivated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactivated_profiles",
                to="admin_area.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
