# Generated by Django 5.2.1 on 2025-07-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0006_alter_profile_subscription_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingsignup",
            name="is_used",
        ),
    ]
