# Generated by Django 5.2 on 2025-05-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0007_scheduledsubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScheduledSubscription",
        ),
    ]
