# Generated by Django 5.2.1 on 2025-08-07 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0008_adminidentity_eventtracker_delete_accounthistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precheckoutemail",
            name="email",
        ),
        migrations.AddField(
            model_name="precheckoutemail",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precheckouts",
                to="admin_area.adminidentity",
            ),
        ),
        migrations.AlterField(
            model_name="eventtracker",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_logs",
                to="admin_area.adminidentity",
            ),
        ),
    ]
