# Generated by Django 5.2 on 2025-05-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0008_delete_scheduledsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
