# Generated by Django 5.2 on 2025-08-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_area",
            "0009_remove_precheckoutemail_email_precheckoutemail_admin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminidentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="eventtracker",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
