# Generated by Django 5.2 on 2025-08-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0010_alter_adminidentity_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_current",
        ),
    ]
