# Generated by Django 5.2 on 2025-05-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0010_scheduledsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsignup",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="stripe_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
