# Generated by Django 5.2 on 2025-08-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0011_remove_profile_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
    ]
