# Generated by Django 5.2 on 2025-05-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0011_pendingsignup_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsignup",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pendingsignup",
            name="stripe_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
