# Generated by Django 5.2 on 2025-05-09 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0012_alter_pendingsignup_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="reactivated_from",
        ),
        migrations.AlterField(
            model_name="profile",
            name="subscription_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
