# Generated by Django 5.2 on 2025-08-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0012_profile_auto_renew"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="auto_renew",
        ),
    ]
