# Generated by Django 5.2 on 2025-05-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0013_rename_created_on_profile_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledsubscription",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="scheduledsubscription",
            name="user",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="reactivated_on",
        ),
        migrations.AlterField(
            model_name="accounthistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("signup", "Signup"),
                    ("cancel", "Cancel Subscription"),
                    ("stripe_payment", "Stripe Payment Processed"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="PendingPlanActivation",
        ),
        migrations.DeleteModel(
            name="ScheduledSubscription",
        ),
    ]
