# Generated by Django 5.2 on 2025-08-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0013_remove_profile_auto_renew"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PreCheckoutEmail",
            new_name="PreCheckout",
        ),
    ]
