# Generated by Django 5.2 on 2025-05-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0014_remove_scheduledsubscription_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounthistory",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="stripe_subscription_id",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="stripe_transaction_id",
        ),
        migrations.RemoveField(
            model_name="pendingsignup",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="pendingsignup",
            name="stripe_transaction_id",
        ),
        migrations.RemoveField(
            model_name="pendingsignup",
            name="subscription_id",
        ),
    ]
