# Generated by Django 5.2 on 2025-08-13 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0014_rename_precheckoutemail_precheckout"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
