# Generated by Django 5.2 on 2025-05-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0015_remove_accounthistory_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_subscription_id",
        ),
    ]
