# Generated by Django 5.2 on 2026-02-18 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0015_profile_profile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("details", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_history",
                        to="admin_area.adminidentity",
                    ),
                ),
                (
                    "source_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_history_entry",
                        to="admin_area.eventtracker",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
            },
        ),
    ]
