# Generated by Django 5.2 on 2026-02-22 22:05

import django.db.models.deletion
import users.admin_area.configs.admin_parameter_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0016_adminaccounthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminParameterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initialized", models.BooleanField(db_index=True, default=False)),
                (
                    "defaults_version_applied",
                    models.CharField(default="v1", max_length=20),
                ),
                (
                    "parameters_json",
                    models.JSONField(
                        default=users.admin_area.configs.admin_parameter_defaults.get_admin_parameter_defaults_v1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_settings",
                        to="admin_area.adminidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Parameter Settings",
                "verbose_name_plural": "Admin Parameter Settings",
                "ordering": ("-updated_at",),
            },
        ),
    ]
