# Generated by Django 5.2 on 2025-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_area",
            "0016_transactionlog_remove_profile_stripe_customer_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthistory",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accounthistory",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accounthistory",
            name="stripe_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="stripe_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
