# Generated by Django 5.2 on 2026-02-22 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0017_adminparametersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminParameterSettingsChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("use_defaults", "Use Defaults"),
                            ("manual_save", "Manual Save"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("changed_paths", models.JSONField(blank=True, default=list)),
                ("before_json", models.JSONField(blank=True, null=True)),
                ("after_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_settings_change_logs",
                        to="admin_area.adminidentity",
                    ),
                ),
                (
                    "parameter_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="admin_area.adminparametersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Parameter Settings Change Log",
                "verbose_name_plural": "Admin Parameter Settings Change Logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
