# Generated by Django 5.2 on 2025-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0017_accounthistory_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
