# Generated by Django 5.2 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0018_adminparametersettingschangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminidentity",
            name="subdomain_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminidentity",
            name="subdomain_slug",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
