# Generated by Django 5.2 on 2025-05-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0018_profile_stripe_subscription_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingsignup",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="pendingsignup",
            name="subscription_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_subscription_id",
        ),
    ]
