# Generated by Django 5.2 on 2025-05-31 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0019_remove_pendingsignup_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounthistory",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="stripe_subscription_id",
        ),
        migrations.RemoveField(
            model_name="accounthistory",
            name="stripe_transaction_id",
        ),
    ]
