# Generated by Django 5.2 on 2026-03-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0020_admindiscountcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminidentity",
            name="marketing_headline",
            field=models.CharField(
                blank=True,
                help_text="Custom marketing headline for this admin's page.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminidentity",
            name="marketing_html",
            field=models.TextField(
                blank=True,
                help_text="Optional custom HTML for this admin's marketing page.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminidentity",
            name="marketing_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to a custom marketing image for this admin's page.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminidentity",
            name="marketing_subheadline",
            field=models.CharField(
                blank=True,
                help_text="Custom marketing subheadline for this admin's page.",
                max_length=300,
                null=True,
            ),
        ),
    ]
