# Generated by Django 5.2 on 2025-05-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0020_remove_accounthistory_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthistory",
            name="stripe_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
