# Generated by Django 5.2 on 2025-05-31 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0021_accounthistory_stripe_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionlog",
            old_name="transaction_id",
            new_name="stripe_transaction_id",
        ),
    ]
