# Generated by Django 5.2 on 2026-03-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0021_adminidentity_marketing_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminidentity",
            name="custom_css_url",
            field=models.URLField(
                blank=True,
                help_text="URL to a custom CSS file for this admin's marketing page.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminidentity",
            name="marketing_theme",
            field=models.CharField(
                blank=True,
                help_text="Theme name for this admin's marketing page (e.g. 'dark', 'red', 'custom').",
                max_length=40,
                null=True,
            ),
        ),
    ]
