# Generated by Django 5.2 on 2026-03-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0022_adminidentity_custom_css_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(
                choices=[
                    ("adminTrial", "Legacy Trial (Deprecated)"),
                    ("adminMonthly", "Monthly Admin Plan"),
                    ("adminQuarterly", "Quarterly Admin Plan"),
                    ("adminAnnual", "Annual Admin Plan"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
