# Generated by Django 5.2 on 2026-03-16 18:53

import json
from pathlib import Path

import django.db.models.deletion
from django.db import migrations, models


def _load_defaults_payload():
    config_dir = Path(__file__).resolve().parents[3] / "core" / "seed_data"

    def _load(name):
        with (config_dir / name).open("r", encoding="utf-8") as handle:
            return json.load(handle)

    global_payload = _load("admin_parameter_defaults_v1_global.json")
    standard_payload = _load("admin_parameter_defaults_v1_standard.json")
    keto_payload = _load("admin_parameter_defaults_v1_keto.json")
    carb_payload = _load("admin_parameter_defaults_v1_carb_cycling.json")

    defaults = global_payload["AdminParametersDefaults"]
    defaults["meal_plans"] = {
        "standard": standard_payload["meal_plans"]["standard"],
        "keto": keto_payload["meal_plans"]["keto"],
        "carb_cycling": carb_payload["meal_plans"]["carb_cycling"],
    }
    return defaults


def seed_admin_parameter_copies(apps, schema_editor):
    defaults = _load_defaults_payload()
    AdminIdentity = apps.get_model("admin_area", "AdminIdentity")
    AdminParameterSettings = apps.get_model("admin_area", "AdminParameterSettings")
    AdminTDEESettings = apps.get_model("admin_area", "AdminTDEESettings")
    AdminStandardSettings = apps.get_model("admin_area", "AdminStandardSettings")
    AdminKetoSettings = apps.get_model("admin_area", "AdminKetoSettings")
    AdminCarbCyclingSettings = apps.get_model("admin_area", "AdminCarbCyclingSettings")

    for identity in AdminIdentity.objects.all():
        settings_obj = AdminParameterSettings.objects.filter(admin=identity).first()
        payload = settings_obj.parameters_json if settings_obj and isinstance(settings_obj.parameters_json, dict) else defaults
        version = (
            (settings_obj.defaults_version_applied if settings_obj else None)
            or payload.get("version")
            or defaults.get("version", "v1")
        )

        goal_adjustments = payload.get("goal_calorie_adjustments") or {}
        tdee = payload.get("tdee") or {}
        AdminTDEESettings.objects.update_or_create(
            admin=identity,
            defaults={
                "defaults_version_applied": version,
                "lose_weight_percent": goal_adjustments.get("lose_weight_percent", -15),
                "maintain_weight_percent": goal_adjustments.get("maintain_weight_percent", 0),
                "gain_weight_percent": goal_adjustments.get("gain_weight_percent", 20),
                "category_multipliers_json": tdee.get("category_multipliers", {}),
                "category_mapping_by_lifestyle_and_training_days_json": tdee.get(
                    "category_mapping_by_lifestyle_and_training_days",
                    {},
                ),
                "weekly_day_multiplier_splits_json": tdee.get("weekly_day_multiplier_splits", {}),
            },
        )

        standard_payload = ((payload.get("meal_plans") or {}).get("standard") or {})
        standard_distribution = standard_payload.get("meal_macro_distribution", {})
        for goal, rule in (standard_payload.get("macro_rules_by_goal") or {}).items():
            AdminStandardSettings.objects.update_or_create(
                admin=identity,
                goal=goal,
                defaults={
                    "defaults_version_applied": version,
                    "protein_factor_unit": rule.get("protein_factor_unit", "g_per_lb"),
                    "protein_factor_value": rule.get("protein_factor_value", 1),
                    "carb_percent": rule.get("carb_percent", 0),
                    "fat_percent": rule.get("fat_percent", 0),
                    "meal_macro_distribution_json": standard_distribution,
                },
            )

        keto_payload = ((payload.get("meal_plans") or {}).get("keto") or {})
        keto_distribution = keto_payload.get("meal_macro_distribution", {})
        for goal, rule in (keto_payload.get("macro_rules_by_goal") or {}).items():
            AdminKetoSettings.objects.update_or_create(
                admin=identity,
                goal=goal,
                defaults={
                    "defaults_version_applied": version,
                    "protein_factor_unit": rule.get("protein_factor_unit", "g_per_lb"),
                    "protein_factor_value": rule.get("protein_factor_value", 1),
                    "carb_percent": rule.get("carb_percent", 0),
                    "fat_percent": rule.get("fat_percent", 0),
                    "meal_macro_distribution_json": keto_distribution,
                },
            )

        carb_payload = ((payload.get("meal_plans") or {}).get("carb_cycling") or {})
        carb_distribution = carb_payload.get("meal_macro_distribution", {})
        for goal, rule in (carb_payload.get("macro_rules_by_goal") or {}).items():
            low_day = rule.get("low_day", {})
            high_day = rule.get("high_day", {})
            AdminCarbCyclingSettings.objects.update_or_create(
                admin=identity,
                goal=goal,
                defaults={
                    "defaults_version_applied": version,
                    "protein_factor_unit": rule.get("protein_factor_unit", "g_per_lb"),
                    "protein_factor_value": rule.get("protein_factor_value", 1),
                    "low_day_carb_percent": low_day.get("carb_percent", 0),
                    "low_day_fat_percent": low_day.get("fat_percent", 0),
                    "high_day_carb_percent": high_day.get("carb_percent", 0),
                    "high_day_fat_percent": high_day.get("fat_percent", 0),
                    "meal_macro_distribution_json": carb_distribution,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0023_alter_plan_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTDEESettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defaults_version_applied",
                    models.CharField(default="v1", max_length=20),
                ),
                (
                    "lose_weight_percent",
                    models.DecimalField(decimal_places=2, default=-15, max_digits=6),
                ),
                (
                    "maintain_weight_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "gain_weight_percent",
                    models.DecimalField(decimal_places=2, default=20, max_digits=6),
                ),
                (
                    "category_multipliers_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "category_mapping_by_lifestyle_and_training_days_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "weekly_day_multiplier_splits_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tdee_settings",
                        to="admin_area.adminidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "TDEE Settings",
                "verbose_name_plural": "TDEE Settings",
                "ordering": ("admin__admin_email",),
            },
        ),
        migrations.CreateModel(
            name="AdminCarbCyclingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defaults_version_applied",
                    models.CharField(default="v1", max_length=20),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "protein_factor_unit",
                    models.CharField(default="g_per_lb", max_length=20),
                ),
                (
                    "protein_factor_value",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "meal_macro_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "low_day_carb_percent",
                    models.DecimalField(decimal_places=3, default=20, max_digits=6),
                ),
                (
                    "low_day_fat_percent",
                    models.DecimalField(decimal_places=3, default=80, max_digits=6),
                ),
                (
                    "high_day_carb_percent",
                    models.DecimalField(decimal_places=3, default=80, max_digits=6),
                ),
                (
                    "high_day_fat_percent",
                    models.DecimalField(decimal_places=3, default=20, max_digits=6),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carb_cycling_settings_rows",
                        to="admin_area.adminidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carb Cycling Settings",
                "verbose_name_plural": "Carb Cycling Settings",
                "ordering": ("admin__admin_email", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admin", "goal"),
                        name="admin_carb_cycling_settings_admin_goal_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminKetoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defaults_version_applied",
                    models.CharField(default="v1", max_length=20),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "protein_factor_unit",
                    models.CharField(default="g_per_lb", max_length=20),
                ),
                (
                    "protein_factor_value",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "meal_macro_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carb_percent",
                    models.DecimalField(decimal_places=3, default=10, max_digits=6),
                ),
                (
                    "fat_percent",
                    models.DecimalField(decimal_places=3, default=90, max_digits=6),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keto_settings_rows",
                        to="admin_area.adminidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keto Settings",
                "verbose_name_plural": "Keto Settings",
                "ordering": ("admin__admin_email", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admin", "goal"),
                        name="admin_keto_settings_admin_goal_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminStandardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defaults_version_applied",
                    models.CharField(default="v1", max_length=20),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "protein_factor_unit",
                    models.CharField(default="g_per_lb", max_length=20),
                ),
                (
                    "protein_factor_value",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "meal_macro_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carb_percent",
                    models.DecimalField(decimal_places=3, default=60, max_digits=6),
                ),
                (
                    "fat_percent",
                    models.DecimalField(decimal_places=3, default=40, max_digits=6),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_settings_rows",
                        to="admin_area.adminidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Settings",
                "verbose_name_plural": "Standard Settings",
                "ordering": ("admin__admin_email", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admin", "goal"),
                        name="admin_standard_settings_admin_goal_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_admin_parameter_copies, migrations.RunPython.noop),
    ]
