# Generated by Django 5.2 on 2026-03-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0024_admintdeesettings_admincarbcyclingsettings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminparametersettingschangelog",
            name="parameter_settings",
        ),
        migrations.AddField(
            model_name="admintdeesettings",
            name="initialized",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.DeleteModel(
            name="AdminParameterSettings",
        ),
    ]
