# Generated by Django 5.2 on 2026-03-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0024_delete_admindiscountcode"),
        (
            "admin_area",
            "0025_remove_adminparametersettingschangelog_parameter_settings_and_more",
        ),
    ]

    operations = []
