# Generated by Django 5.2 on 2026-03-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_area", "0026_merge_20260316_0001"),
        ("admin_area", "0026_merge_20260316_2102"),
    ]

    operations = []
