# Generated by Django 5.2 on 2025-04-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("admin_trial", "Admin Free Trial"),
                    ("admin_monthly", "Admin Monthly"),
                    ("admin_annual", "Admin Annual"),
                    ("admin_inactive", "Admin Inactive"),
                ],
                default="admin_inactive",
                max_length=30,
            ),
        ),
    ]
