# Generated by Django 5.2 on 2025-05-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminpasswordresettoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdminPendingSignup",
        ),
        migrations.DeleteModel(
            name="AdminPlan",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdminPasswordResetToken",
        ),
        migrations.DeleteModel(
            name="AdminProfile",
        ),
    ]
