# Generated by Django 5.2 on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboMacroErrorLookup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("error_code", models.IntegerField(db_index=True, unique=True)),
                ("protein_error", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("carbs_error", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("fats_error", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Combo Macro Error Lookup",
                "verbose_name_plural": "Combo Macro Error Lookups",
                "ordering": ("error_code",),
            },
        ),
        migrations.CreateModel(
            name="FoodLibraryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_food_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("Protein", "Protein"), ("Carbs", "Carbs"), ("Fats", "Fats"), ("-", "-")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("measurement_unit", models.CharField(blank=True, default="oz", max_length=16)),
                ("protein", models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ("carbs", models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ("fats", models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ("is_placeholder", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Food Library Item",
                "verbose_name_plural": "Food Library Items",
                "ordering": ("source_food_id",),
            },
        ),
        migrations.CreateModel(
            name="MealComboTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("combo_id", models.IntegerField(db_index=True, unique=True)),
                ("protein_slot_1", models.CharField(default="-", max_length=120)),
                ("protein_slot_2", models.CharField(default="-", max_length=120)),
                ("carb_slot_1", models.CharField(default="-", max_length=120)),
                ("carb_slot_2", models.CharField(default="-", max_length=120)),
                ("fat_slot_1", models.CharField(default="-", max_length=120)),
                ("fat_slot_2", models.CharField(default="-", max_length=120)),
                ("protein_split_1", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("protein_split_2", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("carb_split_1", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("carb_split_2", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("fat_split_1", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("fat_split_2", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Meal Combo Template",
                "verbose_name_plural": "Meal Combo Templates",
                "ordering": ("combo_id",),
            },
        ),
        migrations.AddIndex(
            model_name="mealcombotemplate",
            index=models.Index(
                fields=["protein_slot_1", "protein_slot_2", "carb_slot_1", "carb_slot_2", "fat_slot_1", "fat_slot_2"],
                name="core_combo_slot_lookup_idx",
            ),
        ),
    ]
