# Generated by Django 5.2 on 2026-03-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_messageattachment_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminParameterDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                ("parameters_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin Parameter Defaults",
                "verbose_name_plural": "Admin Parameter Defaults",
                "ordering": ("-updated_at",),
            },
        ),
    ]
