# Generated by Django 5.2 on 2026-03-16 18:53

import json
from pathlib import Path

from django.db import migrations, models


def _load_defaults_payload():
    config_dir = Path(__file__).resolve().parents[1] / "seed_data"

    def _load(name):
        with (config_dir / name).open("r", encoding="utf-8") as handle:
            return json.load(handle)

    global_payload = _load("admin_parameter_defaults_v1_global.json")
    standard_payload = _load("admin_parameter_defaults_v1_standard.json")
    keto_payload = _load("admin_parameter_defaults_v1_keto.json")
    carb_payload = _load("admin_parameter_defaults_v1_carb_cycling.json")

    defaults = global_payload["AdminParametersDefaults"]
    defaults["meal_plans"] = {
        "standard": standard_payload["meal_plans"]["standard"],
        "keto": keto_payload["meal_plans"]["keto"],
        "carb_cycling": carb_payload["meal_plans"]["carb_cycling"],
    }
    return defaults


def seed_core_parameter_tables(apps, schema_editor):
    payload = _load_defaults_payload()
    version = payload.get("version", "v1")

    TDEEDefault = apps.get_model("core", "TDEEDefault")
    StandardDefault = apps.get_model("core", "StandardDefault")
    KetoDefault = apps.get_model("core", "KetoDefault")
    CarbCyclingDefault = apps.get_model("core", "CarbCyclingDefault")

    TDEEDefault.objects.update_or_create(
        version=version,
        defaults={
            "lose_weight_percent": (payload.get("goal_calorie_adjustments") or {}).get("lose_weight_percent", -15),
            "maintain_weight_percent": (payload.get("goal_calorie_adjustments") or {}).get("maintain_weight_percent", 0),
            "gain_weight_percent": (payload.get("goal_calorie_adjustments") or {}).get("gain_weight_percent", 20),
            "category_multipliers_json": (payload.get("tdee") or {}).get("category_multipliers", {}),
            "category_mapping_by_lifestyle_and_training_days_json": (payload.get("tdee") or {}).get(
                "category_mapping_by_lifestyle_and_training_days",
                {},
            ),
            "weekly_day_multiplier_splits_json": (payload.get("tdee") or {}).get(
                "weekly_day_multiplier_splits",
                {},
            ),
        },
    )

    standard_distribution = ((payload.get("meal_plans") or {}).get("standard") or {}).get("meal_macro_distribution", {})
    for goal, rule in (((payload.get("meal_plans") or {}).get("standard") or {}).get("macro_rules_by_goal") or {}).items():
        StandardDefault.objects.update_or_create(
            version=version,
            goal=goal,
            defaults={
                "protein_factor_unit": rule.get("protein_factor_unit", "g_per_lb"),
                "protein_factor_value": rule.get("protein_factor_value", 1),
                "carb_percent": rule.get("carb_percent", 0),
                "fat_percent": rule.get("fat_percent", 0),
                "meal_macro_distribution_json": standard_distribution,
            },
        )

    keto_distribution = ((payload.get("meal_plans") or {}).get("keto") or {}).get("meal_macro_distribution", {})
    for goal, rule in (((payload.get("meal_plans") or {}).get("keto") or {}).get("macro_rules_by_goal") or {}).items():
        KetoDefault.objects.update_or_create(
            version=version,
            goal=goal,
            defaults={
                "protein_factor_unit": rule.get("protein_factor_unit", "g_per_lb"),
                "protein_factor_value": rule.get("protein_factor_value", 1),
                "carb_percent": rule.get("carb_percent", 0),
                "fat_percent": rule.get("fat_percent", 0),
                "meal_macro_distribution_json": keto_distribution,
            },
        )

    carb_distribution = ((payload.get("meal_plans") or {}).get("carb_cycling") or {}).get("meal_macro_distribution", {})
    for goal, rule in (((payload.get("meal_plans") or {}).get("carb_cycling") or {}).get("macro_rules_by_goal") or {}).items():
        low_day = rule.get("low_day", {})
        high_day = rule.get("high_day", {})
        CarbCyclingDefault.objects.update_or_create(
            version=version,
            goal=goal,
            defaults={
                "protein_factor_unit": rule.get("protein_factor_unit", "g_per_lb"),
                "protein_factor_value": rule.get("protein_factor_value", 1),
                "low_day_carb_percent": low_day.get("carb_percent", 0),
                "low_day_fat_percent": low_day.get("fat_percent", 0),
                "high_day_carb_percent": high_day.get("carb_percent", 0),
                "high_day_fat_percent": high_day.get("fat_percent", 0),
                "meal_macro_distribution_json": carb_distribution,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_adminparameterdefaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbCyclingDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(db_index=True, default="v1", max_length=20),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "protein_factor_unit",
                    models.CharField(default="g_per_lb", max_length=20),
                ),
                (
                    "protein_factor_value",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "meal_macro_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "low_day_carb_percent",
                    models.DecimalField(decimal_places=3, default=20, max_digits=6),
                ),
                (
                    "low_day_fat_percent",
                    models.DecimalField(decimal_places=3, default=80, max_digits=6),
                ),
                (
                    "high_day_carb_percent",
                    models.DecimalField(decimal_places=3, default=80, max_digits=6),
                ),
                (
                    "high_day_fat_percent",
                    models.DecimalField(decimal_places=3, default=20, max_digits=6),
                ),
            ],
            options={
                "verbose_name": "Carb Cycling Default",
                "verbose_name_plural": "Carb Cycling Defaults",
                "ordering": ("version", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="KetoDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(db_index=True, default="v1", max_length=20),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "protein_factor_unit",
                    models.CharField(default="g_per_lb", max_length=20),
                ),
                (
                    "protein_factor_value",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "meal_macro_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carb_percent",
                    models.DecimalField(decimal_places=3, default=10, max_digits=6),
                ),
                (
                    "fat_percent",
                    models.DecimalField(decimal_places=3, default=90, max_digits=6),
                ),
            ],
            options={
                "verbose_name": "Keto Default",
                "verbose_name_plural": "Keto Defaults",
                "ordering": ("version", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="StandardDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(db_index=True, default="v1", max_length=20),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "protein_factor_unit",
                    models.CharField(default="g_per_lb", max_length=20),
                ),
                (
                    "protein_factor_value",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "meal_macro_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carb_percent",
                    models.DecimalField(decimal_places=3, default=60, max_digits=6),
                ),
                (
                    "fat_percent",
                    models.DecimalField(decimal_places=3, default=40, max_digits=6),
                ),
            ],
            options={
                "verbose_name": "Standard Default",
                "verbose_name_plural": "Standard Defaults",
                "ordering": ("version", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="TDEEDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                (
                    "lose_weight_percent",
                    models.DecimalField(decimal_places=2, default=-15, max_digits=6),
                ),
                (
                    "maintain_weight_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "gain_weight_percent",
                    models.DecimalField(decimal_places=2, default=20, max_digits=6),
                ),
                (
                    "category_multipliers_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "category_mapping_by_lifestyle_and_training_days_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "weekly_day_multiplier_splits_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TDEE Default",
                "verbose_name_plural": "TDEE Defaults",
                "ordering": ("version",),
            },
        ),
        migrations.DeleteModel(
            name="AdminParameterDefaults",
        ),
        migrations.AlterModelOptions(
            name="foodlibraryitem",
            options={
                "ordering": ("source_food_id",),
                "verbose_name": "Food Library Default",
                "verbose_name_plural": "Food Library Defaults",
            },
        ),
        migrations.AlterModelOptions(
            name="mealcombotemplate",
            options={
                "ordering": ("combo_id",),
                "verbose_name": "Meal Combo Default",
                "verbose_name_plural": "Meal Combo Defaults",
            },
        ),
        migrations.AddConstraint(
            model_name="carbcyclingdefault",
            constraint=models.UniqueConstraint(
                fields=("version", "goal"),
                name="core_carb_cycling_default_version_goal_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="ketodefault",
            constraint=models.UniqueConstraint(
                fields=("version", "goal"), name="core_keto_default_version_goal_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="standarddefault",
            constraint=models.UniqueConstraint(
                fields=("version", "goal"),
                name="core_standard_default_version_goal_uniq",
            ),
        ),
        migrations.RunPython(seed_core_parameter_tables, migrations.RunPython.noop),
    ]
