# Generated by Django 5.2 on 2026-04-30 08:18

import django.db.models.deletion
from django.db import migrations, models


def seed_banana_peanut_butter_protein_shake(apps, schema_editor):
    FoodLibraryItem = apps.get_model("core", "FoodLibraryItem")
    ProteinShakeTemplate = apps.get_model("core", "ProteinShakeTemplate")
    ProteinShakeIngredientSlot = apps.get_model("core", "ProteinShakeIngredientSlot")

    defaults = {
        "approval_status": "approved",
        "source_type": "standard",
        "is_standard": True,
        "is_active": True,
        "is_placeholder": False,
    }

    def food(source_food_id, name, macro, protein, carbs, fats, unit="serving", basis="Standard serving"):
        row, _ = FoodLibraryItem.objects.update_or_create(
            source_food_id=source_food_id,
            defaults={
                **defaults,
                "name": name,
                "display_name": name,
                "canonical_name": name,
                "category": name,
                "canonical_category": name,
                "macro": macro,
                "measurement_unit": unit,
                "measurement_basis_label": basis,
                "protein": protein,
                "carbs": carbs,
                "fats": fats,
            },
        )
        return row

    protein_powder = food(900001, "Protein Powder STANDARD", "Protein", "24.00000", "3.00000", "2.00000", "scoop", "Per scoop")
    milk = food(900002, "Milk STANDARD", "-", "8.00000", "12.00000", "5.00000", "cup", "Per cup")
    banana = food(900003, "Banana STANDARD", "Carbs", "1.30000", "27.00000", "0.40000", "banana", "Per medium banana")
    peanut_butter_powder = food(900004, "Peanut Butter Powder STANDARD", "Fats", "6.00000", "5.00000", "1.50000", "tbsp", "Per 2 tbsp")
    food(900005, "Honey STANDARD", "Carbs", "0.00000", "17.00000", "0.00000", "tbsp", "Per tbsp")
    food(900006, "Water STANDARD", "-", "0.00000", "0.00000", "0.00000", "cup", "Zero macro liquid")

    template, _ = ProteinShakeTemplate.objects.update_or_create(
        slug="banana-peanut-butter-protein-shake",
        defaults={
            "name": "Banana Peanut Butter Protein Shake",
            "description": "Protein powder with milk, banana, and peanut butter powder. Optional sweetener can be added later.",
            "active": True,
            "default_scoop_count": 1,
            "min_scoop_count": 1,
            "max_scoop_count": 2,
        },
    )

    slots = [
        ("protein_powder", "Protein Powder", True, protein_powder, "1.0000", "scoop", True, False, 1, "protein"),
        ("liquid", "Liquid", False, milk, "1.0000", "cup", True, True, 2, "liquid"),
        ("carb", "Carb", False, banana, "1.0000", "medium banana", True, True, 3, "carb"),
        ("fat_addin", "Fat / Add-in", False, peanut_butter_powder, "2.0000", "tbsp", True, True, 4, "fat"),
        ("sweetener", "Sweetener", False, None, "0.0000", "", True, True, 5, "sweetener"),
    ]
    for slot_key, display_name, required, default_item, amount, unit, allow_override, allow_exclude, sort_order, macro_role in slots:
        ProteinShakeIngredientSlot.objects.update_or_create(
            template=template,
            slot_key=slot_key,
            defaults={
                "display_name": display_name,
                "required": required,
                "default_food_library_item": default_item,
                "default_serving_amount": amount,
                "default_serving_unit": unit,
                "allow_user_override": allow_override,
                "allow_exclude": allow_exclude,
                "sort_order": sort_order,
                "macro_role": macro_role,
            },
        )


def unseed_banana_peanut_butter_protein_shake(apps, schema_editor):
    ProteinShakeTemplate = apps.get_model("core", "ProteinShakeTemplate")
    ProteinShakeTemplate.objects.filter(slug="banana-peanut-butter-protein-shake").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_foodlibraryitem_preparation_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProteinShakeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("default_scoop_count", models.PositiveSmallIntegerField(default=1)),
                ("min_scoop_count", models.PositiveSmallIntegerField(default=1)),
                ("max_scoop_count", models.PositiveSmallIntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Protein Shake Template",
                "verbose_name_plural": "Protein Shake Templates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProteinShakeIngredientSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_key",
                    models.CharField(
                        choices=[
                            ("protein_powder", "Protein Powder"),
                            ("liquid", "Liquid"),
                            ("carb", "Carb"),
                            ("fat_addin", "Fat / Add-in"),
                            ("sweetener", "Sweetener"),
                        ],
                        max_length=40,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("required", models.BooleanField(default=False)),
                (
                    "default_serving_amount",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
                (
                    "default_serving_unit",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("allow_user_override", models.BooleanField(default=True)),
                ("allow_exclude", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "macro_role",
                    models.CharField(
                        choices=[
                            ("protein", "Protein"),
                            ("carb", "Carb"),
                            ("fat", "Fat"),
                            ("liquid", "Liquid"),
                            ("sweetener", "Sweetener"),
                        ],
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_food_library_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protein_shake_default_slots",
                        to="core.foodlibraryitem",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_slots",
                        to="core.proteinshaketemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protein Shake Ingredient Slot",
                "verbose_name_plural": "Protein Shake Ingredient Slots",
                "ordering": ("template_id", "sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "slot_key"),
                        name="core_unique_shake_template_slot",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_banana_peanut_butter_protein_shake, unseed_banana_peanut_butter_protein_shake),
    ]
